module.exports = {
	'bodyParser' : 'body-parser'
	, 'queryParser' : 'connect-query'
	, 'cookieParser' : 'cookie-parser'
	, 'router' : 'express-optimized'
	, 'responseTime' : 'response-time'
	, 'static' : 'serve-static'
	, 'compress' : 'compression'
	, 'mount' : './lib/mount'
	, '_404' : './lib/404'
	, 'route' : './lib/route'
	, 'express' : './lib/express'
	, 'redirect' : './lib/redirect'
	, 'params' : './lib/params'
	, 'locals' : './lib/locals'
	, 'set' : './lib/set'
	, 'header' : './lib/header'
	, 'end' : './lib/end'
	, 'status' : './lib/status'
	, 'originalUrl' : './lib/original-url'
	, 'session' : 'express-session'
};
